logging:
  level:
    ROOT: DEBUG
    "[org.hibernate.SQL]": DEBUG
    "[com.chf.gateway]": DEBUG    
   
spring:
  devtools:
    restart:
      enabled: true
      additional-exclude: static/**,.h2.server.properties
    livereload:
      enabled: false # we use Webpack dev server + BrowserSync for livereload
  jackson:
    serialization:
      indent-output: true
  cloud:
    consul:
      config:
        fail-fast: false # if not in "prod" profile, do not force to use Spring Cloud Config
        format: yaml
        profile-separator: ','
      discovery:
        prefer-ip-address: true
        tags:
          - profile=${spring.profiles.active}
          - version=#project.version#
      host: localhost
      port: 8500
  h2:
    console:
      # disable spring boot built-in h2-console since we start it manually with correct configuration
      enabled: false
  messages:
    cache-duration: PT1S # 1 second, see the ISO 8601 standard
  sql:
    init:
      mode: never
  r2dbc:
#    url: r2dbc:h2:file:./target/h2db/app-uua;DB_CLOSE_DELAY=-1
#    username: app
#    password: null
    url: r2dbc:mysql://localhost:3306/app-uua?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true
    username: root
    password: root
  thymeleaf:
    cache: false
  zipkin: # Use the "zipkin" Maven profile to have the Spring Cloud Zipkin dependencies
    base-url: http://localhost:9411
    enabled: false
    locator:
      discovery:
        enabled: true

server:
  port: 8081

app:
  gateway:
    rate-limiting:
      enabled: false
      limit: 100000
      duration-in-seconds: 3600
  cors:
    allowed-origins: '*'
#    allowed-methods: 'GET, PUT, POST, DELETE, OPTIONS'
    allowed-methods: '*'
    allowed-headers: '*'
    exposed-headers: "Authorization,Link,X-Total-Count"
    allow-credentials: true
    max-age: 1800
    